'use client'
import { useState, useEffect } from 'react'
import { useCart } from '@/hooks/use-cart'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetFooter } from '@/components/ui/sheet'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import { getProducts } from '@/lib/db/actions'
import { Search, ShoppingCart, Plus, Minus, Trash2, X, Package } from 'lucide-react'
import Link from 'next/link'
import { toast } from 'sonner'
export default function StorePage() { const [products, setProducts] = useState<any[]>([]);
const [loading, setLoading] = useState(true);
const [search, setSearch] = useState('');
const [category, setCategory] = useState('all');
const { addItem, items, totalItems, totalAmount, isOpen, setIsOpen, removeItem, updateQuantity } = useCart();
 useEffect(() => { async function load() { try { const data = await getProducts() setProducts(data.filter((p: any) => p.current_stock > 0 && !p.deleted_at)) } finally { setLoading(false) } } load() }, []);
const categories = ['all', ...Array.from(new Set(products.map(p => p.category).filter(Boolean)))];
const filtered = products.filter(p => { const matchSearch = !search || p.name.toLowerCase().includes(search.toLowerCase()) || (p.sku && p.sku.toLowerCase().includes(search.toLowerCase()))
const matchCat = category === 'all' || p.category === category return matchSearch && matchCat });
const cartItemMap = new Map(items.map(i => [i.id, i]));
return ( <div className='min-h-screen bg-muted/30'> {/* Header */} <header className='sticky top-0 z-40 bg-background/95 backdrop-blur border-b'> <div className='max-w-7xl mx-auto px-4 h-14 flex items-center justify-between gap-4'> <div className='flex items-center gap-2'> <div className='w-8 h-8 rounded-lg bg-primary flex items-center justify-center'> <span className='text-primary-foreground font-bold text-sm'>PB</span> </div> <span className='font-semibold text-sm hidden sm:inline'>Store</span> </div> <div className='flex-1 max-w-md'> <div className='relative'> <Search className='absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground' /> <Input placeholder='Search products...' className='pl-9 h-9' value={search} onChange={e => setSearch(e.target.value)} /> </div> </div> <Button variant='outline' size='sm' className='relative' onClick={() => setIsOpen(true)}> <ShoppingCart className='w-4 h-4 mr-2' /> Cart {totalItems > 0 && ( <Badge className='absolute -top-2 -right-2 h-5 w-5 p-0 flex items-center justify-center text-[10px]'> {totalItems} </Badge> )} </Button> </div> </header> {/* Categories */} <div className='max-w-7xl mx-auto px-4 py-3'> <div className='flex gap-2 overflow-x-auto pb-1 scrollbar-hide'> {categories.map(cat => ( <Button key={cat} variant={category === cat ? 'default' : 'outline'} size='sm' className='shrink-0 capitalize text-xs' onClick={() => setCategory(cat)} > {cat} </Button> ))} </div> </div> {/* Products Grid */} <main className='max-w-7xl mx-auto px-4 pb-8'> {loading ? ( <div className='grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3'> {Array.from({ length: 10 }).map((_, i) => ( <Skeleton key={i} className='h-56 w-full rounded-xl' /> ))} </div> ) : filtered.length === 0 ? ( <div className='text-center py-20 text-muted-foreground'> <Package className='w-12 h-12 mx-auto mb-3 opacity-50' /> <p>No products found</p> </div> ) : ( <div className='grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3'> {filtered.map(product => { const inCart = cartItemMap.get(product.id);
const maxAdd = product.current_stock - (inCart?.quantity || 0);
return ( <Card key={product.id} className='border-0 shadow-sm hover:shadow-md transition-shadow group'> <CardContent className='p-0'> <div className='aspect-square bg-muted rounded-t-xl flex items-center justify-center'> <Package className='w-10 h-10 text-muted-foreground/40' /> </div> <div className='p-3 space-y-2'> <div> <p className='font-medium text-sm line-clamp-2 leading-tight'>{product.name}</p> <p className='text-xs text-muted-foreground'>{product.sku || product.category || 'Product'}</p> </div> <div className='flex items-center justify-between'> <p className='font-bold text-sm'>₹{product.selling_price?.toLocaleString()}</p> <p className='text-[10px] text-muted-foreground'>{product.current_stock} left</p> </div> {inCart ? ( <div className='flex items-center gap-1'> <Button variant='outline' size='icon' className='h-7 w-7' onClick={() => updateQuantity(product.id, inCart.quantity - 1)}> <Minus className='w-3 h-3' /> </Button> <span className='w-8 text-center text-sm font-medium'>{inCart.quantity}</span> <Button variant='outline' size='icon' className='h-7 w-7' onClick={() => { if (maxAdd > 0) { addItem({ id: product.id, name: product.name, price: product.selling_price || 0, stock: product.current_stock,
sku: product.sku }) }
else { toast.error('Max stock reached') } }} > <Plus className='w-3 h-3' /> </Button> </div> ) : ( <Button className='w-full h-8 text-xs' size='sm' onClick={() => addItem({ id: product.id, name: product.name, price: product.selling_price || 0, stock: product.current_stock,
sku: product.sku })} disabled={product.current_stock <= 0} > <Plus className='w-3 h-3 mr-1' /> Add </Button> )} </div> </CardContent> </Card> ) )} </div> )} </main> {/* Cart Drawer */} <Sheet open={isOpen} onOpenChange={setIsOpen}> <SheetContent className='w-full sm:max-w-md flex flex-col'> <SheetHeader className='pb-3'> <SheetTitle className='flex items-center gap-2'> <ShoppingCart className='w-5 h-5' /> Your Cart ({totalItems}) </SheetTitle> </SheetHeader> <ScrollArea className='flex-1 -mx-6 px-6'> {items.length === 0 ? ( <div className='text-center py-12 text-muted-foreground'> <ShoppingCart className='w-10 h-10 mx-auto mb-3 opacity-40' /> <p className='text-sm'>Your cart is empty</p> <p className='text-xs mt-1'>Add products to get started</p> </div> ) : ( <div className='space-y-3'> {items.map(item => ( <div key={item.id} className='flex gap-3 p-3 rounded-lg bg-muted/50'> <div className='w-14 h-14 bg-muted rounded-lg flex items-center justify-center shrink-0'> <Package className='w-6 h-6 text-muted-foreground/40' /> </div> <div className='flex-1 min-w-0'> <p className='text-sm font-medium truncate'>{item.name}</p> <p className='text-xs text-muted-foreground'>₹{item.price.toLocaleString()} each</p> <div className='flex items-center gap-2 mt-1'> <Button variant='outline' size='icon' className='h-6 w-6' onClick={() => updateQuantity(item.id, item.quantity - 1)}> <Minus className='w-3 h-3' /> </Button> <span className='w-6 text-center text-sm font-medium'>{item.quantity}</span> <Button variant='outline' size='icon' className='h-6 w-6' onClick={() => { if (item.quantity < item.stock) { updateQuantity(item.id, item.quantity + 1) }
else { toast.error('Max stock reached') } }} > <Plus className='w-3 h-3' /> </Button> <Button variant='ghost' size='icon' className='h-6 w-6 ml-auto text-red-500' onClick={() => removeItem(item.id)}> <Trash2 className='w-3 h-3' /> </Button> </div> </div> <div className='text-right shrink-0'> <p className='text-sm font-semibold'>₹{(item.price * item.quantity).toLocaleString()}</p> </div> </div> ))} </div> )} </ScrollArea> {items.length > 0 && ( <> <Separator className='my-3' /> <div className='space-y-3'> <div className='flex justify-between text-sm'> <span className='text-muted-foreground'>Subtotal</span> <span className='font-medium'>₹{totalAmount.toLocaleString()}</span> </div> <div className='flex justify-between text-lg font-bold'> <span>Total</span> <span>₹{totalAmount.toLocaleString()}</span> </div> <Link href='/checkout' onClick={() => setIsOpen(false)}> <Button className='w-full'>Proceed to Checkout</Button> </Link> <Button variant='ghost' size='sm' className='w-full text-muted-foreground' onClick={() => {
if (confirm('Clear all items?')) { items.forEach(i => removeItem(i.id)) } }} > Clear Cart </Button> </div> </> )} </SheetContent> </Sheet> </div> ) }